Repository GSG-G8/room-booker, pull requests merged in 2020-04, with the labels that each got.

#42 POST login
  .github/workflows/tests.yml
  package-lock.json
  package.json
  server/__test__/database.test.js
  server/__test__/router.test.js
  server/package.json
  server/src/controllers/index.js
  server/src/controllers/login.js
  server/src/controllers/validation/loginSchema.js
  server/src/controllers/validation/loginValidation.js
  server/src/database/config/build.js
  server/src/database/config/connection.js
  server/src/database/config/fakedata.sql
  server/src/database/queries/checkEmail.js
  server/src/router.js
  server/src/utils/jwt.js
Labels: in progress

#48 13 get users redo
  server/__test__/getUsers.test.js
  server/__test__/index.test.js
  server/package.json
  server/src/controllers/getUsers.js
  server/src/controllers/index.js
  server/src/controllers/middleware/checkAdmin.js
  server/src/controllers/middleware/index.js
  server/src/controllers/middleware/verifyUser.js
  server/src/database/queries/getUserById.js
  server/src/database/queries/getUsers.js
  server/src/database/queries/index.js
  server/src/router.js
  server/src/utils/jwt.js
Labels: Highest Priority

#47 delete user by id
  server/__test__/database.test.js
  server/__test__/router.test.js
  server/src/controllers/deleteUser.js
  server/src/controllers/index.js
  server/src/controllers/login.js
  server/src/database/queries/deleteUserById.js
  server/src/database/queries/index.js
  server/src/router.js
  server/src/utils/jwt.js
Labels: pending

#49 GET rooms/:date
  server/__test__/database.test.js
  server/__test__/router.test.js
  server/src/controllers/booking.js
  server/src/controllers/index.js
  server/src/database/queries/getBookingbydate.js
  server/src/database/queries/index.js
  server/src/router.js
Labels: waiting-review

#62 12 post booking
  server/__test__/booking.test.js
  server/__test__/database.test.js
  server/__test__/router.test.js
  server/package-lock.json
  server/package.json
  server/src/controllers/booking.js
  server/src/controllers/index.js
  server/src/controllers/validation/bookingSchema.js
  server/src/database/config/fakedata.sql
  server/src/database/queries/Booking.js
  server/src/database/queries/addRoom.js
  server/src/database/queries/booking.js
  server/src/database/queries/index.js
  server/src/router.js
  server/src/utils/moment-range.js
Labels: waiting-review
